# Site settings
title: Jennifer and Eamon
email: info@jenniferandeamon.com
description: > # this means to ignore newlines until "baseurl:"
  Test Description Line 1
  Test Description Line 2
  Test Descrption Line 3
baseurl: "" # the subpath of your site, e.g. /rsvp
url: "https://www.jenniferandeamon.com" # the base hostname & protocol for your site
production_url: "https://www.jenniferandeamon.com"
github_username: eamon3
permalink: /rsvp/:year/:month/:title.html

twitter:
  username: twitter.username

# Google Analytics
google_analytics_tracking_id: UA-0000000-11

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
